@startuml





/' Objects '/

class BaseballPlayer {
	+BaseballPlayer(const double battingAverage, const int homeRuns)
	+~BaseballPlayer()
	-battingAverage_ : double
	-homeRuns_ : int
	-{static} EDAD_MINIMA : static constexpr int
	+queSoy() : std::string
	+queSoyVirtual() : std::string
}





/' Inheritance relationships '/




/' Aggregation relationships '/



@enduml
